### ISSUE TITLE
Will you provide the code and dataset?

### ISSUE THREAD

**Issue by beatrizmarauj** [Chocolife-96/Priority-Branches-for-Ship-Detection-in-Optical-Remote-Sensing-Images#2]
In your article "Priority Branches for Ship Detection in Optical Remote Sensing Images" you said you are going to provide the code and dataset in this github. Please, could you provide it?

**Comment by Chocolife-96** [comment]
hi，the code hae been provided. However, for the sake of national security, the images in our dataset should be reviewed carefully before being released. Sorry for that.
